### ISSUE TITLE
Issure related with AIC and BIC

### ISSUE THREAD

**Issue by ivangtorre** [Jaimemosg/EstimationTools#1]
I reproduce a bug in the estimation of BIC
```
set.seed(10)
x <- rnorm( n = 10000, mean = 160, sd = 6 )
fit <- maxlogL( x = x, dist = "dnorm", link = list(over = "sd", fun = "log_link") )
summary(fit)

MaxLogLikelihood <- fit$fit$objective
```

The result of this code is: 
AIC = 64328.7    BIC =64324.7
MaxLogLikelihood = -32162.35

AIC looks well but BIC is deprecating the first term:
BIC should be: 
BIC = log(n)*k - 2*MaxLogLikelihood

It is easy shown that its just calculated doing 
BIC = - 2*MaxLogLikelihood

**Comment by Jaimemosg** [comment]
Dear @ivangtorre:

Thank you for your interest in `EstimationTools`. When I perform your test, I note that in that with the function `BIC(fit)`, I obtain `64343.12`, but with `AIC`, I get `64324.7`.

On the other hand, if you compute "manually" information criteria:

```
BIC_fit <- -2*as.numeric(logLik(fit)) + log(10000)*2
AIC_fit <- -2*as.numeric(logLik(fit))
```

You are going to obtain the same results. Finally, with a different data set
```
y <- rnorm( n = 10000, mean = 0, sd = 20 )
fit_2 <- maxlogL( x = y, dist = "dnorm", link = list(over = "sd", fun = "log_link") )
summary(fit_2)
```

the results are as follows:
AIC = 88459.35; BIC = 88473.77

which can be verified in the same way as previously I did.
Please, let me know if you have more issues with our package.

Best wishes.

## ----- Edit -----
I must correct this post. Firstly, it is more suitable to fix a seed for the example
```
set.seed(0308)
y <- rnorm( n = 10000, mean = 0, sd = 20 )
fit_2 <- maxlogL( x = y, dist = "dnorm", link = list(over = "sd", fun = "log_link") )
summary(fit_2)
```
![image](https://user-images.githubusercontent.com/37384444/89194051-79827b00-d56c-11ea-993b-3f6aa069c971.png)

And AIC formula I applied before was wrong. Then I write it correctly:

```
k <- 2
BIC_fit <- -2*as.numeric(logLik(fit)) + log(10000)*k
AIC_fit <- -2*as.numeric(logLik(fit)) + 2*k
```

And this leads us to the same results for AIC and BIC

![image](https://user-images.githubusercontent.com/37384444/89194891-9a979b80-d56d-11ea-9242-785010d130ae.png)

Finally, I want to show that your command to take the maximum log-likelihood is correct, and equivalent to use the `loglik` generic method:

![image](https://user-images.githubusercontent.com/37384444/89194354-dd0ca880-d56c-11ea-9f74-fff91e289656.png)

**Comment by ivangtorre** [comment]
Sorry but with your code and using same sed I obtain:

> ---------------------------------------------------------------
Optimization routine: nlminb 
Standard Error calculation: Hessian from optim 
---------------------------------------------------------------
       AIC      BIC
  88459.35 88455.35
---------------------------------------------------------------
     Estimate  Std. Error
mean  0.066909     0.2016
sd   20.162588     0.1426
-----

where again BIC is not giving a food result.
Thanks

**Comment by Jaimemosg** [comment]
Let's go back to the first example:

```
set.seed(10)
x <- rnorm( n = 10000, mean = 160, sd = 6 )
fit <- maxlogL( x = x, dist = "dnorm", link = list(over = "sd", fun = "log_link") )
summary(fit)
```

The output is as follows
```
_______________________________________________________________
Optimization routine: nlminb 
Standard Error calculation: Hessian from optim 
_______________________________________________________________
      AIC      BIC
  64328.7 64343.12
_______________________________________________________________
     Estimate  Std. Error Z value Pr(>|z|)    
mean 160.00803    0.06033  2652.1   <2e-16 ***
sd     6.03331    0.04266   141.4   <2e-16 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1
_______________________________________________________________
Note: p-values valid under asymptotic normality of estimators 
---
```

When you type `AIC` and `BIC`, this leads to the same results of te summary:

```
> AIC(fit)
[1] 64328.7
> BIC(fit)
[1] 64343.12
```

Let me show a screenshot:

![image](https://user-images.githubusercontent.com/37384444/89192676-75555e00-d56a-11ea-9edf-b2b06cf438a5.png)

Computing manually, we get the same results for AIC and BIC:

```
BIC_fit <- -2*as.numeric(logLik(fit)) + log(10000)*2
AIC_fit <- -2*as.numeric(logLik(fit)) + 2*2
```

whose results are 64343.12 and 64328.7 respectively

![image](https://user-images.githubusercontent.com/37384444/89192740-928a2c80-d56a-11ea-8352-fab2b6f18ea0.png)

Again, thanks for your interest and your comments about our package. This help us to enhance it and continuously grow.
Best wishes.
